version: "3.8"

services:
  wordle-backend:
    build:
      context: .
      dockerfile: projects/wordle-buddy/backend/Dockerfile
    container_name: wordle_backend
    ports:
      - "8000:8000"
    volumes:
      - ./projects/wordle-buddy/backend:/app
    restart: unless-stopped
